### PR TITLE
Fixes #6

### LINKED ISSUE #6: OS X Support
It would be cool if you could get some of the configurations working for OS X. I've installed it and this is what I see:
http://i.imgur.com/uKSMfAb.png

Although besides that it works fine. Also a note on installing it for other OS X users, you have to make sure you've installed MPC with:

`brew install mpc`

Then follow the directions in this guide to install MPD: http://mpd.wikia.com/wiki/Mpd_on_OS_X_Snow_Leopard

### PR DESCRIPTION
**Pull request by frm**
Fix for #6
Adds OS X support:
- Fixed iTunes information
- Enabled app launching
- Fixed disk display info

Current state: 
about-blank-osx

I think the Ram info could be displayed in a friendlier way, but I don't know how I can make it better.
If you have any ideas or want me to change anything, I'll gladly update it.

### CODE REVIEW

**Comment by wbrbr** [comment]
Can't you use `exec` instead of `open -a` on Mac ?

**Comment by frm** [comment]
As far as I could tell, you were grabbing the string of the command/bin name and running it with `ChildProcess#exec()`, which is fine on Linux since they probably are included in `$PATH`.

OS X is a bit different. Installed apps are contained in `/Applications` or `/Users/<user>/Applications`. In there, the executables are in a .app directory. They aren't really contained in `$PATH` and the most common way to run them is using `open -a`.

I completely forgot to mention that in the PR, since I'm changing `public/client.js`. Sorry about that.

An alternative to use a different client for OS X would be to check `navigator.platform` and see if it matches Mac.

**Comment by wbrbr** [comment]
The client.js should now check `navigator.platform`, it works on Linux. Could you try and tell me if it works ? Thanks for your help :+1:

**Comment by frm** [comment]
Sorry it took me so long. Yes, I can confirm that the app launch on the OS X version is working.

**Comment by wbrbr** [comment]
Ok, I merged the branch in `master`. Thanks for your help :+1:

**Pull request merged**
